package com.antra.ticket;
import jakarta.validation.constraints.Min; import java.math.BigDecimal; import java.util.*; import org.springframework.beans.factory.annotation.Value; import org.springframework.http.*; import org.springframework.kafka.core.KafkaTemplate; import org.springframework.security.core.Authentication; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.bind.annotation.*; import org.springframework.web.client.RestClient;
@RestController @RequestMapping("/api/reservations") class TicketController { private final ReservationRepository repo; private final RestClient events; private final KafkaTemplate<String,Object> kafka;
 TicketController(ReservationRepository repo,KafkaTemplate<String,Object> kafka,@Value("${services.event.url:http://event-service:8082}") String url){this.repo=repo;this.kafka=kafka;events=RestClient.builder().baseUrl(url).build();}
 @PostMapping @Transactional ResponseEntity<Reservation> reserve(Authentication auth,@RequestHeader("Authorization") String bearer,@RequestParam(name="eventId") Long eventId,@RequestParam(name="quantity") @Min(1) int quantity){Map r=events.post().uri("/api/events/{id}/reserve?quantity={q}",eventId,quantity).header("Authorization",bearer).retrieve().body(Map.class); BigDecimal price=new BigDecimal(r.get("unitPrice").toString()); Reservation saved=repo.save(new Reservation(auth.getName(),eventId,quantity,price)); kafka.send("reservation-created",saved.id.toString(),Map.of("reservationId",saved.id,"username",saved.username,"eventId",eventId,"total",saved.totalPrice));return ResponseEntity.status(201).body(saved);}
 @GetMapping List<Reservation> mine(Authentication auth){return repo.findByUsernameOrderByCreatedAtDesc(auth.getName());}
 @GetMapping("/{id}") Reservation one(@PathVariable("id") Long id,Authentication auth){Reservation r=repo.findById(id).orElseThrow();if(!r.username.equals(auth.getName()))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.FORBIDDEN);return r;}
 @PutMapping("/{id}/cancel") @Transactional Reservation cancel(@PathVariable("id") Long id,Authentication auth,@RequestHeader("Authorization") String bearer){Reservation r=one(id,auth);if("PAID".equals(r.status))throw new org.springframework.web.server.ResponseStatusException(HttpStatus.CONFLICT);r.status="CANCELLED";events.post().uri("/api/events/{id}/release?quantity={q}",r.eventId,r.quantity).header("Authorization",bearer).retrieve().toBodilessEntity();return r;}
}
