import { Component, EventEmitter, inject, Output, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient, HttpErrorResponse } from '@angular/common/http';

@Component({selector:'app-admin-dashboard',standalone:true,imports:[CommonModule,FormsModule],template:`<section class="admin"><h2>Event manager</h2><p>Publish an event for your audience.</p><form (ngSubmit)="publish()"><label>Event title<input name="title" [(ngModel)]="form.title" required></label><label>Venue<input name="venue" [(ngModel)]="form.venue" required></label><label>Start date & time<input name="startsAt" [(ngModel)]="form.startsAt" [min]="minimumStartDateTime" type="datetime-local" required></label><label>Ticket price<input name="price" [(ngModel)]="form.price" type="number" min="0.01" step="0.01" required></label><label>Capacity<input name="capacity" [(ngModel)]="form.capacity" type="number" min="1" required></label><label class="wide">Description<textarea name="description" [(ngModel)]="form.description"></textarea></label><label class="wide">Banner image<input name="banner" (change)="chooseFile($event)" type="file" accept="image/jpeg,image/png,image/webp"></label><button [disabled]="saving()">{{saving()?'Publishing…':'Publish event'}}</button></form><p class="message" *ngIf="message()">{{message()}}</p></section>`,styles:[`.admin{margin-top:45px;padding:28px;border-radius:12px;background:#f5f1ff}.admin h2{margin:0}.admin form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:18px}.wide{grid-column:1/-1}label{display:grid;gap:5px;font-weight:600}input,textarea{padding:10px;border:1px solid #c9c3d8;border-radius:6px;font:inherit}textarea{min-height:70px}.admin button{width:max-content}.message{font-weight:600;color:#4b168f}`]})
export class AdminDashboardComponent {
  private http=inject(HttpClient); @Output() eventPublished=new EventEmitter<void>(); saving=signal(false); message=signal(''); file?:File;
  minimumStartDateTime=this.toDateTimeLocal(new Date(Date.now()+60_000)); form={title:'',venue:'',startsAt:'',price:25,capacity:100,description:''};
  chooseFile(event:Event){this.file=(event.target as HTMLInputElement).files?.[0];}
  publish(){const startsAt=new Date(this.form.startsAt);if(!this.form.startsAt||Number.isNaN(startsAt.getTime()))return this.finish('Choose a valid event start date and time.');if(startsAt.getTime()<=Date.now())return this.finish('The event start date and time must be in the future.');this.saving.set(true);this.message.set('');this.http.post<any>('/api/events',{...this.form,startsAt:startsAt.toISOString()}).subscribe({next:e=>this.uploadBanner(e.id),error:(error:HttpErrorResponse)=>this.finish(error.status===401||error.status===403?'Your admin session is not authorized. Sign in again.':error.error?.message||'Event creation failed.')});}
  private uploadBanner(eventId:number){if(!this.file){this.finish('Event published.');this.eventPublished.emit();return;}const file=this.file;this.http.post<{uploadUrl:string;publicUrl:string}>(`/api/events/${eventId}/banner/upload-url`,null,{params:{contentType:file.type}}).subscribe({next:async signed=>{try{const response=await fetch(signed.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!response.ok)throw new Error();this.http.put(`/api/events/${eventId}/banner`,{url:signed.publicUrl}).subscribe({next:()=>{this.finish('Event and banner published.');this.eventPublished.emit();},error:()=>this.finish('Image uploaded, but attaching its URL failed.')});}catch{this.finish('S3 image upload failed. Check storage configuration.');}},error:()=>this.finish('Could not request an upload URL. Check storage configuration.')});}
  private finish(message:string){this.saving.set(false);this.message.set(message);}
  private toDateTimeLocal(date:Date){const offset=date.getTimezoneOffset();return new Date(date.getTime()-offset*60_000).toISOString().slice(0,16);}
}
