import { Component, inject, signal } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({selector:'app-admin-dashboard',standalone:true,imports:[CommonModule,FormsModule],template:`<section class="admin"><h2>Event manager</h2><p>Publish events and upload their banner images directly to protected S3 storage.</p><div *ngIf="!admin()" class="auth"><input [(ngModel)]="username" placeholder="Admin username"><input [(ngModel)]="password" type="password" placeholder="Password"><button (click)="signIn()">Admin sign in</button></div><form *ngIf="admin()" (ngSubmit)="publish()"><label>Event title<input name="title" [(ngModel)]="form.title" required></label><label>Venue<input name="venue" [(ngModel)]="form.venue" required></label><label>Start date & time<input name="startsAt" [(ngModel)]="form.startsAt" type="datetime-local" required></label><label>Ticket price<input name="price" [(ngModel)]="form.price" type="number" min="0.01" step="0.01" required></label><label>Capacity<input name="capacity" [(ngModel)]="form.capacity" type="number" min="1" required></label><label class="wide">Description<textarea name="description" [(ngModel)]="form.description"></textarea></label><label class="wide">Banner image<input name="banner" (change)="chooseFile($event)" type="file" accept="image/jpeg,image/png,image/webp"></label><button [disabled]="saving()">{{saving()?'Publishing…':'Publish event'}}</button></form><p class="message" *ngIf="message()">{{message()}}</p></section>`,styles:[`.admin{margin-top:45px;padding:28px;border-radius:12px;background:#f5f1ff}.admin h2{margin:0}.auth,form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px;margin-top:18px}.wide{grid-column:1/-1}label{display:grid;gap:5px;font-weight:600}input,textarea{padding:10px;border:1px solid #c9c3d8;border-radius:6px;font:inherit}textarea{min-height:70px}.admin button{width:max-content}.message{font-weight:600;color:#4b168f}`]})
export class AdminDashboardComponent {
  private http=inject(HttpClient); admin=signal(this.role()==='ADMIN'); saving=signal(false); message=signal(''); username=''; password=''; file?:File;
  form={title:'',venue:'',startsAt:'',price:25,capacity:100,description:''};
  private role(){try{return JSON.parse(atob((localStorage.getItem('token')||'').split('.')[1]||'')).role}catch{return ''}}
  signIn(){this.http.post<{token:string}>('/api/auth/login',{username:this.username,password:this.password}).subscribe({next:r=>{localStorage.setItem('token',r.token);this.admin.set(this.role()==='ADMIN');this.message.set(this.admin()?'Admin access granted.':'This account is not an administrator.');},error:()=>this.message.set('Sign-in failed.')});}
  chooseFile(event:Event){this.file=(event.target as HTMLInputElement).files?.[0];}
  publish(){this.saving.set(true);this.message.set('');const payload={...this.form,startsAt:new Date(this.form.startsAt).toISOString()};this.http.post<any>('/api/events',payload).subscribe({next:event=>this.uploadBanner(event.id),error:()=>this.finish('Event creation failed. Confirm your admin access.')});}
  private uploadBanner(eventId:number){if(!this.file){this.finish('Event published.');return;}const file=this.file;this.http.post<{uploadUrl:string;publicUrl:string}>(`/api/events/${eventId}/banner/upload-url`,null,{params:{contentType:file.type}}).subscribe({next:async signed=>{try{const response=await fetch(signed.uploadUrl,{method:'PUT',headers:{'Content-Type':file.type},body:file});if(!response.ok)throw new Error();this.http.put(`/api/events/${eventId}/banner`,{url:signed.publicUrl}).subscribe({next:()=>this.finish('Event and banner published.'),error:()=>this.finish('Image uploaded, but attaching its URL failed.')});}catch{this.finish('S3 image upload failed. Check AWS bucket CORS and IAM configuration.');}},error:()=>this.finish('Could not request an upload URL. Check S3 configuration.')});}
  private finish(message:string){this.saving.set(false);this.message.set(message);}
}
